# Generated by Django 6.0.3 on 2026-03-10 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_api', '0001_initial'),
        ('services', '0002_alter_appointment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='services.appointment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('appointment_booked', 'Appointment Booked'), ('appointment_completed', 'Appointment Completed'), ('appointment_canceled', 'Appointment Canceled'), ('appointment_reminder', 'Appointment Reminder'), ('voucher_created', 'Voucher Created')], max_length=30),
        ),
    ]
