# Generated by Django 6.0.3 on 2026-03-06 19:03

import django.db.models.deletion
import grooming_salon.utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[grooming_salon.utils.validators.validate_capitalized_name])),
                ('date_of_birth', models.DateField()),
                ('breed', models.CharField(max_length=50, validators=[grooming_salon.utils.validators.validate_capitalized_name])),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/dogs/', validators=[grooming_salon.utils.validators.validate_file_size])),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to=settings.AUTH_USER_MODEL)),
                ('notes', models.ManyToManyField(blank=True, related_name='dogs', to='dogs.note')),
            ],
        ),
    ]
