# Generated by Django 6.0.3 on 2026-03-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_api', '0002_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyalty',
            name='used_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
