# Generated by Django 6.0.3 on 2026-03-10 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_api', '0003_loyalty_used_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyalty',
            name='points',
        ),
    ]
